<?php
/**
 * @file
 * Code for the OE Relationship: Performer module.
 */

include_once 'oe_relationship_performer.field_base.inc';
include_once 'oe_relationship_performer.field_instance.inc';
include_once 'oe_relationship_performer.rdf_mapping.inc';

/**
 * Implements hook_ctools_plugin_api().
 */
function oe_relationship_performer_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "relation" && $api == "relation_type_default") {
    return array("version" => "1");
  }
}
