<?php
/**
 * @file
 * Code for the OE Person module.
 */

include_once 'oe_person.field_base.inc';
include_once 'oe_person.field_instance.inc';
include_once 'oe_person.taxonomy.inc';
include_once 'oe_person.user_permission.inc';
include_once 'oe_person.rdf_mapping.inc';

/**
 * Implements hook_install().
 */
function oe_person_install() {

  oe_person_field_bases();
  oe_person_field_instances();
  oe_person_user_permissions();
  oe_person_rdf_mapping();
  oe_person_taxonomy_title();

}

/**
 * Implements hook_ctools_plugin_api().
 */
function oe_person_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function oe_person_node_info() {
  $items = array(
    'person' => array(
      'name' => t('Person'),
      'base' => 'node_content',
      'description' => t('Open Event content type for a person (alive, dead, undead, or fictional).<br/>
Designed in accordance with the <a href="http://schema.org/Person" target="_blank">Schema.org Person type</a>.'),
      'has_title' => '1',
      'title_label' => t('Person name'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
