<?php


  /*
   * @file
   * OE Schema.org Image module - Provides Schema.org mappings for image fields
   */

  /**
   * Implements hook_schemaorg_rest_field_alter
   *
   * Map image fields to Schema.org ImageObject
   */
  function oe_schemaorg_rest_image_schemaorg_rest_field_alter(&$value, &$term, &$field_info) {
    if (($term == 'schema:image' || $term == 'schema:logo') && $field_info['type'] == 'image') {
      // handle multi-value image fields
      if ($field_info['cardinality'] != 1 && !isset($value['file'])) {
        foreach(array_keys($value) as $index) {
          oe_schemaorg_rest_image_schemaorg_rest_field_alter($value[$index], $term, $field_info);
        }
      }
      else {
        // mappings from Drupal's image representation to Schema.org representation
        $imageMappings = array('alt'=>'alternateName', 'title'=>'caption', 'file'=>'contentUrl');

        $newImage = array();
        foreach ($value as $key => $fieldValue) {
          // get the URL to the file from its ID
          if ($key == 'file') {
            $file = file_load($fieldValue['id']);
            $uri = $file->uri;
            $url = file_create_url($uri);
            $newImage[$imageMappings[$key]] = $url;
          }
          // other (text) fields can be mapped as-is
          else {
            $newImage[$imageMappings[$key]] = $fieldValue;
          }
        }

        $value = $newImage;
      }
    }
  }
