<?php
/**
 * @file
 * Code for the OE Organization module.
 */

include_once 'oe_organization.field_base.inc';
include_once 'oe_organization.field_instance.inc';
include_once 'oe_organization.user_permission.inc';
include_once 'oe_organization.rdf_mapping.inc';

function oe_organization_install() {

  oe_organization_field_bases();
  oe_organization_field_instances();
  oe_organization_user_permissions();
  oe_organization_rdf_mapping();

  // Set default variables
  variable_set('field_bundle_settings_node__organization', array(
    'view_modes' => array(
      'teaser' => array(
        'custom_settings' => TRUE,
      ),
      'full' => array(
        'custom_settings' => FALSE,
      ),
      'rss' => array(
        'custom_settings' => FALSE,
      ),
      'token' => array(
        'custom_settings' => FALSE,
      ),
    ),
    'extra_fields' => array(
      'form' => array(
        'title' => array(
          'weight' => '1',
        ),
        'path' => array(
          'weight' => '4',
        ),
      ),
      'display' => array(),
    ),
  ));

  variable_set('menu_options_organization', array());
  variable_set('menu_parent_organization', 'main-menu:0');
  variable_set('node_options_organization', array());
  variable_set('node_preview_organization', '0');
  variable_set('node_submitted_organization', 0);

}

/**
 * Implements hook_ctools_plugin_api().
 */
function oe_organization_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "relation" && $api == "relation_type_default") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function oe_organization_node_info() {
  $items = array(
    'organization' => array(
      'name' => t('Organization'),
      'base' => 'node_content',
      'description' => t('Open Event content type for an organization, such as a school, NGO, corporation, club, etc.<br/>
Designed in accordance with the <a href="http://schema.org/Organization" target="_blank">Schema.org organization type</a>.'),
      'has_title' => '1',
      'title_label' => t('Organization name'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
