<?php
/**
 * @file
 * Code for the OE Place module.
 */

include_once 'oe_place.field_base.inc';
include_once 'oe_place.field_instance.inc';
include_once 'oe_place.user_permission.inc';
include_once 'oe_place.rdf_mapping.inc';

function oe_place_install() {

  oe_place_field_bases();
  oe_place_field_instances();
  oe_place_user_permissions();
  oe_place_rdf_mapping();

  // Set default variables
  variable_set('field_bundle_settings_node__place', array(
    'view_modes' => array(
      'teaser' => array(
        'custom_settings' => TRUE,
      ),
      'full' => array(
        'custom_settings' => FALSE,
      ),
      'rss' => array(
        'custom_settings' => FALSE,
      ),
      'token' => array(
        'custom_settings' => FALSE,
      ),
    ),
    'extra_fields' => array(
      'form' => array(
        'title' => array(
          'weight' => '1',
        ),
        'path' => array(
          'weight' => '6',
        ),
      ),
      'display' => array(),
    ),
  ));

  variable_set('menu_options_place', array());
  variable_set('menu_parent_place', 'main-menu:0');
  variable_set('node_options_place', array());
  variable_set('node_preview_place', '0');
  variable_set('node_submitted_place', 0);

}

/**
 * Implements hook_ctools_plugin_api().
 */
function oe_place_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "relation" && $api == "relation_type_default") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function oe_place_node_info() {
  $items = array(
    'place' => array(
      'name' => t('Place'),
      'base' => 'node_content',
      'description' => t('Open Event content type for a place (entities that have a somewhat fixed, physical extension).<br />Designed in accordance with the <a href="https://schema.org/Place" target="_blank">Schema.org Place type</a>.'),
      'has_title' => '1',
      'title_label' => t('Place name'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
