<?php
/**
 * @file
 * Code for the OE Event module.
 */

include_once 'oe_event.field_base.inc';
include_once 'oe_event.field_instance.inc';
include_once 'oe_event.user_permission.inc';
include_once 'oe_event.rdf_mapping.inc';

function oe_event_install() {

  oe_event_field_bases();
  oe_event_field_instances();
  oe_event_user_permissions();
  oe_event_rdf_mapping();

  // Set default variables
  variable_set('field_bundle_settings_node__event', array(
    'view_modes' => array(
      'teaser' => array(
        'custom_settings' => TRUE,
      ),
      'full' => array(
        'custom_settings' => FALSE,
      ),
      'rss' => array(
        'custom_settings' => FALSE,
      ),
      'token' => array(
        'custom_settings' => FALSE,
      ),
    ),
    'extra_fields' => array(
      'form' => array(
        'title' => array(
          'weight' => '1',
        ),
        'path' => array(
          'weight' => '6',
        ),
      ),
      'display' => array(),
    ),
  ));

  variable_set('menu_options_event', array());
  variable_set('menu_parent_event', 'main-menu:0');
  variable_set('node_options_event', array());
  variable_set('node_preview_event', '0');
  variable_set('node_submitted_event', 0);

}

/**
 * Implements hook_ctools_plugin_api().
 */
function oe_event_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "field_validation" && $api == "default_field_validation_rules") {
    return array("version" => "2");
  }
  if ($module == "relation" && $api == "relation_type_default") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function oe_event_node_info() {
  $items = array(
    'event' => array(
      'name' => t('Event'),
      'base' => 'node_content',
      'description' => t('Open Event content type for an event happening at a certain time and location, such as a concert, lecture, or festival. Repeated events may be structured as separate Event objects.<br/>
Designed in accordance with the <a href="https://schema.org/Event" target="_blank">Schema.org Event type</a>.'),
      'has_title' => '1',
      'title_label' => t('Event name'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
